// Engine and index persistence facade.
//
// Kept as a thin indirection for incremental DB migration.

export {
  cleanupZeroHolders,
  closeDb,
  countHolders,
  countSubscribers,
  deleteSubscription,
  deleteUserAgent,
  getActiveIndexes,
  getAgentRotationEvents,
  getAgentRotationPolicy,
  getAllIndexes,
  getAllUserAgents,
  getDecisionsByAgent,
  getEquityByAgent,
  getGlobalFeed,
  getHolder,
  getHoldersByIndex,
  getIndex,
  getIndexFeed,
  getIndexTrades,
  getOracleSnapshots,
  getSubscriptionsByAgent,
  getSubscriptionsByIndex,
  getTradesByAgent,
  rawDb,
  saveAgentRotationEvent,
  saveDecision,
  saveEquityPoint,
  saveFeedEvent,
  saveIndexStateBatch,
  saveIndexTrade,
  saveOracleSnapshot,
  saveTrade,
  saveUserAgent,
  saveUserAgentsBatch,
  upsertHolder,
  upsertIndex,
  upsertSubscription,
} from './db.js'
